

SELECT * FROM  USUARIO WITH (NOLOCK);
SELECT * FROM  CARRO WITH (NOLOCK);




-- SELECT GERAL
SELECT * FROM USUARIO WITH (NOLOCK)
INNER JOIN CARRO ON USUARIO.UsuarioID = CARRO.CarroID 




-- SELECT COM COLUNAS
SELECT USUARIO.UsuarioID, Nome, Sexo, DataNascimento, Idade, Email,
Marca, Modelo, Ano, Cor, KM
FROM USUARIO WITH (NOLOCK)
INNER JOIN CARRO ON USUARIO.UsuarioID = CARRO.CarroID
